### PR TITLE
[#159] terminate felix process when ext gets deactivated

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
fixes #159

**Comment by jrichter1** [comment]
I think you should stop the server using its API, that way it ensures the state is persisted and the connection is disposed. There is a method for that in the client:

https://github.com/redhat-developer/rsp-client/blob/master/USAGE.md#connection-handling

**Comment by jeffmaury** [comment]
+1 one with @jrichter1 suggestion

**Comment by jrichter1** [comment]
LGTM

**Pull request merged**
