### PR TITLE
Issue #156: Already existing servers are not displayed in the Servers view

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by mohitsuman** [comment]
testPR

**Comment by mohitsuman** [comment]
@jeffmaury The persistence is not working as expected.
If we select any server(say Wildfly 13) in one window and keep it Started/Stopped state, and then open a new window. Then the rsp-server throws an error as Address already in use.

Here is the error trace: https://pastebin.com/1hLWYYF1

**Comment by jeffmaury** [comment]
You are probably refering to #134

**Comment by dgolovin** [comment]
@jeffmaury right, new window as I understand loads extensions again and that means another instance of rsp-server is created. It fails to start on the same port until we release #134.

**Comment by dgolovin** [comment]
testPR

**Pull request merged**
