### PR TITLE
Update to allow sending deployment options

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Comment by robstryker** [comment]
testPR

**Comment by robstryker** [comment]
testPR

**Comment by jeffmaury** [comment]
Can't we force the user to edit deployment options when the selected file / folder does not have extension instead of asking ?

**Comment by robstryker** [comment]
@fbricon  Not really. What if there's some type of server adapter that's not a j2ee one, which is perfectly capable of handling, say, a folder with no extension? For example, imagine a server adapter that is really just an ftp client or something. You can "publish" a folder of pdfs if you want. The deployment could be the folder and it can republish whenever one of the contents changes. 

I guess we could allow a server adapter type to declare some of its deployment options mandatory, but that wouldn't really work for this case, because if the user selects a "blah.war" folder,  the deployment_name option wouldn't be mandatory.  It would only be mandatory when a folder with no extension was chosen. So if the RSP tells the client deployment_name is mandatory, but then the user selects a blah.war folder, well then it isn't mandatory, right? 

So instead the RSP would need to say deployment_name is a mandatory deployment option IF X Y Z ETC ETC,  which now becomes a very complicated API to do in advance. If a client says "Hey RSP, give me the deployment options for wildfly 15",  should the server say deployment_name is mandatory? The wildfly adapter would probably say "um... i have some mandatory ones, some optional, and some that may be mandatory or optional depending on what you're trying to publish"  and then the workflow becomes extremely confused. 

See, being given a list of options,  option A is mandatory, option B is optional.  That's kinda easy.  But transmitting over API a list of options and a CONDITIONAL mandatory-optional status would now become a disaster. What types of conditions need to be part of the API? Should arbitrary sever types be able to add their own arbitrary conditions? What if an option is mandatory if your web.xml has a given entry, but optional if it doesn't?  How could an RSP protocol ever satisify such wide-ranging conditions? How could a client / UI be able to present or validate any random conditions in advance?  The answer the client can't, and the client shouldn't.  It'd be an impossible workflow. 

It all comes down to workflow between client and server. The current workflow is that the client, before knowing ANYTHING AT ALL about the deployment, asks the server "give me your deployment options", and then the client find a file/folder, prompt for all options,a dn then send a request with options set. 

If we had options that were mandatory or optional in given circumstances, the workflow would be quite frankly dizzying. Client would ask for a list of options, server would reply with some mandatory, some optional, and then some with conditions attached. Client would need to know how to handle any of those conditions. As the list of possible conditions increased, clients would need to know to expand their capability of handling those conditions. Would these conditions be considered part of the RSP API? If yes, then they should be centralized somehow.  However centralizing these conditions would make it impossible for server adapters to customize their own conditions for certain flags. This would actually hurt the freedom of server adapters substantially. 

So no... I don't believe it's smart or prudent for an RSP to support the idea of possibly-but-not-always-required deployment options and sending conditions for under what circumstances those options are in fact required and how a client should validate that they are fulfilled. The RSP adapter should simply reject any deployment that does not meet it's requirements dynamically.

**Comment by robstryker** [comment]
testPR

**Pull request merged**
