### PR TITLE
Generate coverage report for unit test 

### PR DESCRIPTION
**Pull request by sudhirverma**

### CODE REVIEW

**Comment by dgolovin** [comment]
Original code is here https://rpeshkov.net/blog/vscode-extension-coverage

**Comment by mohitsuman** [comment]
@sudhirverma can you resolve the conflicts and push the changes. Please do not push force. :)

**Comment by mohitsuman** [comment]
@sudhirverma you have pushed 12 commits in addition with your commit.

**Comment by sudhirverma** [comment]
testPR

**Comment by dgolovin** [comment]
test this

**Pull request merged**
