### PR TITLE
Update Readme with build snapshot location change

### LINKED ISSUE #161: Update Readme with snapshot location change
The build snapshot location will change as mentioned in https://github.com/redhat-developer/vscode-adapters/pull/158/commits/be87d1996618cd8d64ae024a1f67dc0670c01a40#diff-58231b16fdee45a03a4ee3cf94a9f2c3R59

Hence update the README accordingly.

### PR DESCRIPTION
**Pull request by mohitsuman**

### CODE REVIEW

**Comment by jeffmaury** [comment]
We probably need naming convention for PR as Fix #xxx is not meaningful enough for me

**Comment by mohitsuman** [comment]
@jeffmaury acknowledged. Updated the description for the PR.

**Comment by dgolovin** [comment]
testPR

**Comment by jrichter1** [comment]
testPR

**Pull request merged**
